env:
  es6: true
  browser: true
extends: airbnb
rules:
  arrow-parens:
    - 2
    - always
    - requireForBlockBody: true
  arrow-body-style:
    - 2
    - always
  no-confusing-arrow:
    - 2
    - allowParens: false
  no-console:
    - 2
    - allow:
        - warn
        - info
        - error
  comma-dangle: 
    - error
    - never